packages:
  - packages/*

overrides:
  mdast-util-gfm-autolink-literal: 2.0.0

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

catalog:
  'class-variance-authority': ^0.7.1
  'next-auth': ^4.24.13
  'tw-animate-css': ^1.3.7
  '@ant-design/cssinjs': ^1.24.0
  '@ant-design/icons': ^5.6.1
  '@ant-design/nextjs-registry': ^1.3.0
  '@ant-design/x': ^1.6.1
  '@auth/prisma-adapter': ^2.10.0
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.29.7
  '@eslint/compat': ^1.3.0
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.24.0
  '@fingerprintjs/fingerprintjs': ^4.6.2
  '@heroicons/react': ^2.2.0
  '@prisma/client': ^6.1.0
  '@radix-ui/react-dialog': ^1.1.14
  '@radix-ui/react-slot': ^1.2.3
  '@rsbuild/core': ^1.3.22
  '@rsbuild/plugin-less': ^1.2.2
  '@rsbuild/plugin-react': ^1.2.0
  '@rsbuild/plugin-source-build': ^1.0.3
  '@rslib/core': ^0.12.4
  '@storybook/addon-essentials': ^8.6.14
  '@storybook/addon-interactions': ^8.6.12
  '@storybook/addon-links': ^8.6.12
  '@storybook/addon-onboarding': ^8.6.12
  '@storybook/blocks': ^8.6.12
  '@storybook/react': ^8.6.12
  '@storybook/test': ^8.6.12
  '@svgdotjs/svg.js': ^3.2.4
  '@tailwindcss/postcss': ^4
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.3.0
  '@toolkit-fe/clipboard': ^0.1.22
  '@toolkit-fe/where-am-i': ^0.1.22
  '@trivago/prettier-plugin-sort-imports': ^5.2.2
  '@types/bcryptjs': ^3.0.0
  '@types/hast': ^3.0.4
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.14.1
  '@types/pako': ^2.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@types/react-syntax-highlighter': ^15.5.13
  ahooks: ^3.8.4
  antd: ^6.0.0
  antd-style: ^3.7.1
  bcryptjs: ^3.0.2
  classnames: ^2.5.1
  clsx: ^2.1.1
  dayjs: ^1.11.18
  dompurify: ^3.2.5
  echarts-for-react: ^3.0.2
  emoji-dictionary: ^1.0.12
  eslint: ^9.26.0
  eslint-config-next: ^16.0.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^6.1.0
  globals: ^16.0.0
  hast: ^1.0.0
  husky: ^9.1.7
  jose: ^6.0.11
  jsdom: ^26.1.0
  katex: ^0.16.22
  lint-staged: ^15.5.1
  lodash-es: ^4.17.21
  lucide-react: ^0.508.0
  mermaid: ^11.11.0
  next: ^16.0.7
  pako: ^2.1.0
  prettier: ^3.5.3
  prettier-plugin-tailwindcss: ^0.7.0
  prisma: ^6.1.0
  pure-react-router: ^0.2.4
  react: ^19.2.1
  react-dom: ^19.2.1
  react-infinite-scroll-component: ^6.1.0
  react-markdown: ^10.1.0
  react-photo-view: ^1.2.7
  react-syntax-highlighter: ^15.6.1
  rehype-katex: ^7.0.1
  rehype-raw: ^7.0.0
  remark-breaks: ^4.0.0
  remark-gfm: ^4.0.1
  remark-math: ^6.0.0
  remark-mermaidjs: '4'
  storybook: ^8.6.12
  storybook-addon-rslib: ^1.0.3
  storybook-react-rsbuild: ^1.0.1
  tailwind-merge: ^3.3.0
  tailwindcss: ^3
  tsx: ^4.20.6
  typescript: ^5.8.3
  typescript-eslint: ^8.30.1
  vaul: ^1.1.2
  vitest: ^3.2.3
  zustand: ^5.0.6
  zod: ^3.25.0
